package constants

const (
	Unable_TO_CREATE_REQUEST_OBJECT = 452
	Unable_TO_UNMARSHALL_JSON       = 453
	Unable_TO_READ_REQUEST_DATA     = 454
	Unable_TO_CREATE_CLIENT_OBJECT  = 455
)

// 460 series
const (
	UNABLE_TO_VALIDATE_REQUEST             = 460
	FIRST_MATCH_EMTPY                      = 461
	OVERLAPPING_KEYS_FIRST_ALWAYS_MATCH    = 461
	MISSING_ALWAYS_FIRST_MATCH_CAPABILITES = 462
)

// 470 series Misc
const (
	UNABLE_TO_CREATE_DEPLOYMENT = 471
)
